config/routes.rb
Jigso::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  match '/feed' => 'entries#index',
        :as => :feed,
        :defaults => { :format => 'atom' }
        
  match 'home' => 'home#index'
  match 'settings' => 'settings#index'
  match 'settings/app' => 'settings#app'

  root :to => "main#index"

  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users

  resources :entries do
    member do
      post 'follow'
      post 'unfollow'
    end
    resources :photos, :only => [:create, :destroy]
    resources :votes, :only => [:create, :destroy]
  end  

  resources :items do
    resources :entries
    resources :votes, :only => [:create, :destroy]
  end
  resources :user_items, :only => [:create, :destroy]

  resources :pages

  namespace :api do 
    namespace :v1 do
      resources :entries
    end
  end    
  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :title, :body, :attachments_attributes, :tag_list, :item_id
  # attr_accessor :keep_the_item
  has_many   :attachments, :as => :attachable, :dependent => :destroy
  belongs_to :user
  belongs_to :item

  accepts_nested_attributes_for :attachments, :allow_destroy => true
  default_scope order('created_at DESC')

  make_voteable
  acts_as_taggable
  acts_as_followable

  self.per_page = 10

  include ActiveRecord::Transitions

  state_machine do 
    state :draft
    state :published
    event :publish do
      transitions :to => :published, :from => :draft #, :on_transition => :do_publish
    end
  end
  
  auto_html_for :body do
    html_escape
    image
    youtube(:width => 400, :height => 250)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  # activity streams  
  fires :new_entry, :on => :create, :actor => :user, :secondary_subject => :item

  # callbacks
  before_save do |entry|
    # add user_items automatically
    if entry.item_id
      # item = Item.find_or_create_by_url(entry.item_id)
      # item.users << entry.user if entry.keep_the_item
    end  
  end

  after_destroy do |entry|
    # remove all related events
  end  
  


  # scopes & utility methods
  def related_entries; find_related_tags end

end


# == Schema Information
#
# Table name: entries
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  body       :text
#  body_html  :text
#  item_id    :integer
#  user_id    :integer
#  state      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  up_votes   :integer         default(0), not null
#  down_votes :integer         default(0), not null
#

app/controllers/api/v1/entries_controller.rb
class Api::V1::EntriesController < Api::V1::BaseController

  def index
    respond_with(current_user.entries.all)
  end
  
  def create
    entry = current_user.entries.create(params[:entry])
    if entry.valid?
      respond_with(entry, :location => api_v1_entry_path(entry))
    else
      respond_with(entry)
    end    
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_item, :only => [:create]
  respond_to :html, :json
  respond_to :atom, :only => :index

  inherit_resources
  load_and_authorize_resource

  def index
    # @recent_events = current_user.recent_events.limit(10)
    @entries = Entry.order('created_at DESC')
    @entries = @entries.tagged_with(params[:tag]) if params[:tag]
    @entries = @entries.page(params[:page])
    respond_with(@entries)
  end

  def new
    @entry = Entry.new(:item_id => params[:item_id])
  end  

  def create
    @entry = current_user.entries.build(params[:entry])
    @entry.item = @item
    create!
  end
  
  def follow
    @entry = Entry.find(params[:id])
    current_user.follow(@entry)
    flash[:notice] = "You are now following this item."
    redirect_to :back
  end
  
  def unfollow
    @entry = Entry.find(params[:id])
    current_user.stop_following(@entry)
    flash[:notice] = "You are now stop following this item."
    redirect_to :back
  end
  
  private
  
  def find_item
    @item ||= Item.find(params[:item_id])
  end  

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div class="entry clearfix">
	<%#= link_to image_tag(first_image(entry.body_html), :width => 80, :height => 80, :class => 'thumb'), entry %>
	<% if entry.item %>
		<%= link_to image_tag(entry.item.image, :width => 70, :class => 'thumb'), entry.item %>
	<% end %>	
	<div class="content">
		<%= link_to image_tag(entry.user.gravatar_url(:size => 40), :class => 'avatar') %>
		<!-- <h5><%= link_to entry.title, entry %></h5> -->
    <p><%= strip_tags(entry.body_html).truncate(100) %></p>
		<div class="comment_count">
			<%= link_to "0 Comments", entry_path(entry, :anchor => 'disqus_thread') %>
		</div>	
	</div>	
</div>

app/views/entries/_form.html.erb
<%= nested_form_for [@entry.item, @entry], :html => { :multipart => true } do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :rows => 5 %>
  </div>

	<div class="field">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
	</div>	

	<%= f.fields_for :attachments do |attachment_form|  %>
		<p>
			<%= attachment_form.label :file %>
			<%= attachment_form.file_field :file %>
		</p>
		<p>
			<%= attachment_form.label :description %>
			<%= attachment_form.text_area :description, :rows => 2 %>
		</p>
		<%= attachment_form.link_to_remove "Remove this attachment" %>
	<% end %>
	<%= f.link_to_add "Add attachment", :attachments %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<div class="header">
	<%= button_link_to "New Entry", new_entry_path, :class => 'minimal' %>
</div>

<h2><%=page_title "Recent Entries" %></h2>

<ul id="recent_entries" class="entries">
	<%= render @entries %>
</ul>

<%= will_paginate @entries, :class => 'digg_pagination' %>

<% content_for :sub do %>
<h5>Tags</h5>
<% tag_cloud(Entry.tag_counts_on(:tags), %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, entries_path(:tag => tag.name) , :class => css_class %>
<% end %>
<% end %>

<% content_for :javascript do %>
	<%= render 'shared/disqus/comment_count' %>
<script type="text/javascript" charset="utf-8">
</script>
<% end %>	

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<div>
	<%= link_to 'Back', entries_path %> |
	<%= link_to 'Edit', edit_entry_path(@entry), :class => "#{'hidden' if cannot?(:update, @entry)}" %> |
	<%= link_to 'Destroy', @entry, :confirm => 'Are you sure?', :method => :delete,
							:class => "#{'hidden' if cannot?(:destroy, @entry)}" %>
</div>

<h3><%=title @entry.title %></h3>
<div class="header">
	<abbr class="timeago" title="<%= @entry.created_at(:to_db) %>"><%= @entry.created_at.to_s(:short) %></abbr>
	by <%= @entry.user %>
</div>	

<div class="body">
	<%= @entry.body_html %>
</div>

<div class="tags">
	<h5>Tags</h5>
	<%=raw @entry.tags.map { |t| link_to(t) }.join(', ') %>
</div>

<div class="votes">
	<h5>Vote</h5>
	<% if current_user && current_user.voted?(@entry) %>
		당신은 이 항목을 <%= current_user.up_voted?(@entry) ? '좋아' : '싫어' %> 합니다. 
		<%= link_to "취소", entry_vote_path(@entry, 1), :method => 'delete' %>
	<% else %>
		<%= link_to "좋아요", entry_votes_path(@entry, :flag => 'up'), :method => 'post' %>: <%= @entry.up_votes %> |
		<%= link_to "싫어요", entry_votes_path(@entry, :flag => 'down'), :method => 'post' %>: <%= @entry.down_votes %>
	<% end %>	
</div>	

<ul>
  <% @entry.attachments.each do |attachment| %>
    <li>
    <%= attachment.description %> - <%= link_to("Download", attachment.file_url) %>
    </li>
  <% end %>
</ul>

<hr />

<h5>Related Entries</h5>
<ul class="entries empty">
	<%= render @entry.related_entries %>
</ul>

<hr />

<h5>Comments</h5>
<%= render 'shared/disqus/disqus' %>

<% content_for :side do %>
	<h5><%= @entry.user_followers.size %> Followers</h5>
	<%=raw @entry.user_followers.map { |u| link_to(image_tag(u.photo(:thumb))) }.join(' ') %>
	<div>
		<% if current_user.try(:following?, @entry) %>
			You're following this. 
			[<%= link_to 'Unfollow', unfollow_entry_path(@entry), :method => :post %>]
		<% else %>						
			<%= link_to 'Follow This', follow_entry_path(@entry), :method => :post %>
		<% end %>	
	</div>	
<% end %>

<% content_for :javascript do %>
	<%= render 'shared/disqus/comment_count' %>
<% end %>