config/routes.rb
Jigso::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  match '/feed' => 'entries#index',
        :as => :feed,
        :defaults => { :format => 'atom' }
        
  match 'home' => 'home#index'
  match 'settings' => 'settings#index'
  match 'settings/app' => 'settings#app'

  root :to => "main#index"

  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users

  resources :entries do
    member do
      post 'follow'
      post 'unfollow'
    end
    resources :photos, :only => [:create, :destroy]
    resources :votes, :only => [:create, :destroy]
  end  

  resources :items do
    resources :entries
    resources :votes, :only => [:create, :destroy]
  end
  resources :user_items, :only => [:create, :destroy]

  resources :pages

  namespace :api do 
    namespace :v1 do
      resources :entries
    end
  end    
  

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
  
  def app
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_tabs.html.erb
<ul class="tabs">
	<li><%= link_to "Profile", settings_path, :class => "#{'active' if active == 'settings' }" %></li>
  <li><%= link_to "Account", edit_user_registration_path, :class => "#{'active' if active == 'account' }" %></li>
  <li><%= link_to "Application", "/settings/app", :class => "#{'active' if active == 'app' }" %></li>
</ul>

app/views/settings/app.html.erb
<h2><%= page_title "Settings / Application" %></h2>
<%= render 'tabs', :active => 'app' %>

<h3>API authentication</h3>
<div class="box">
	Your auth_token: <strong><%= current_user.authentication_token %></strong>
</div>	


<h3>Other Settings</h3>

<%= simple_form_for current_user do |f| %>
	<%= f.fields_for :prefs, current_user.prefs do |p| %>

		<div class="box">
			<% UserPreference::DEFAULT_OPTIONS.keys.each do |key| %>
				<%= p.input key, :as => :boolean %>
			<% end %>
		</div>	

	<% end %>
	<%= f.button :submit %>
<% end %>

app/views/settings/index.html.erb
<h2><%= page_title "Settings" %></h2>

<%= render 'tabs', :active => 'settings' %>

TBD. What goes here?