config/routes.rb
Jigso::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  match '/feed' => 'entries#index',
        :as => :feed,
        :defaults => { :format => 'atom' }
        
  match 'home' => 'home#index'
  match 'settings' => 'settings#index'
  match 'settings/app' => 'settings#app'

  root :to => "main#index"

  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users

  resources :entries do
    member do
      post 'follow'
      post 'unfollow'
    end
    resources :photos, :only => [:create, :destroy]
    resources :votes, :only => [:create, :destroy]
  end  

  resources :items do
    resources :entries
    resources :votes, :only => [:create, :destroy]
  end
  resources :user_items, :only => [:create, :destroy]

  resources :pages

  namespace :api do 
    namespace :v1 do
      resources :entries
    end
  end    
  

end

app/models/timeline_event.rb
class TimelineEvent < ActiveRecord::Base
  belongs_to :actor,              :polymorphic => true
  belongs_to :subject,            :polymorphic => true
  belongs_to :secondary_subject,  :polymorphic => true
  
  default_scope order('created_at DESC')

end

# == Schema Information
#
# Table name: timeline_events
#
#  id                     :integer         not null, primary key
#  event_type             :string(255)
#  subject_type           :string(255)
#  actor_type             :string(255)
#  secondary_subject_type :string(255)
#  subject_id             :integer
#  actor_id               :integer
#  secondary_subject_id   :integer
#  created_at             :datetime
#  updated_at             :datetime
#

app/views/timeline_events/_new_entry.html.erb
<div class="activity new_entry">
	<%= link_to(event.actor, user_url(event.actor)) %>
	created a <%= link_to "new entry", event.subject %>
	<% if event.secondary_subject %>
		about an <%= link_to 'item', event.secondary_subject %>
	<% end %>
	<abbr class="timeago" title="<%= event.created_at(:to_db) %>"><%= event.created_at.to_s(:short) %></abbr>
  <!-- <div class="body">
		<%= strip_tags(event.subject.body_html).truncate(100) %>
	</div> -->
	<%= render 'entries/entry', :entry => event.subject %>
</div>

app/views/timeline_events/_new_item.html.erb
<div class="activity new_item">
	<%= link_to(event.actor, user_url(event.actor)) %>
	add a <%= link_to "new item", event.subject.item %>
	<abbr class="timeago" title="<%= event.created_at(:to_db) %>"><%= event.created_at.to_s(:short) %></abbr>
	<%= render 'items/item', :item => event.secondary_subject %>
</div>