config/routes.rb
Jigso::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  match '/feed' => 'entries#index',
        :as => :feed,
        :defaults => { :format => 'atom' }
        
  match 'home' => 'home#index'
  match 'settings' => 'settings#index'
  match 'settings/app' => 'settings#app'

  root :to => "main#index"

  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users

  resources :entries do
    member do
      post 'follow'
      post 'unfollow'
    end
    resources :photos, :only => [:create, :destroy]
    resources :votes, :only => [:create, :destroy]
  end  

  resources :items do
    resources :entries
    resources :votes, :only => [:create, :destroy]
  end
  resources :user_items, :only => [:create, :destroy]

  resources :pages

  namespace :api do 
    namespace :v1 do
      resources :entries
    end
  end    
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :user_items
  has_many :users, :through => :user_items, :uniq => true
  has_many :entries #, :primary_key => :url
  validates_presence_of :title, :url
  validates_uniqueness_of :url
  default_scope order('created_at DESC')

  make_voteable

  # def related_entries
  #   Entry.where(:item_id => self.key)
  # end
  
  def image
    image_url.blank? ? Settings.item.default_image : image_url
  end

end


# == Schema Information
#
# Table name: items
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  url         :string(255)
#  image_url   :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  inherit_resources
  
  def index
    @items = current_user.items
  end
  
  def show
    @item = Item.includes(:entries).find(params[:id])
    @users = @item.users - [current_user]
  end

  def create
    @item = Item.find_by_url(params[:item][:url]) || Item.create(params[:item])
    UserItem.create(:user => current_user, :item => @item)
    redirect_to @item
  end
  
  def add
    @item = Item.find(params[:id])
    current_user.items << @item
    redirect_to :back
  end
  
  def remove
    @item = Item.find(params[:id])
    current_user.items.delete @item
    redirect_to :back
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
	<%= f.input :title, :input_html => { :title => "#{@item.title || 'Enter Item title'}" } %>
	<%= f.input :url, :as => :string, :label => 'Item URL', :input_html => { :title => "#{@item.url || 'Enter Item URL'}" } %>
	<%= f.input :image_url, :as => :string, :label => "Image URL" %>
	<%= f.input :description, :input_html => { :rows => 3 } %>
	<%= f.button :submit %>	
<% end %>

app/views/items/_item.html.erb
<div class="item clearfix">
	<%= link_to image_tag(item.image, :width => 70, :class => 'thumb'), item %>
	<div class="content">
		<h5><%= link_to item.title, item %></h5>
		<%= link_to item.url, item.url %>
		<p>
			<%= strip_tags(item.description).truncate(100) %>
		</p>	
	</div>	
</div>	

app/views/items/edit.html.erb
<h2><%= page_title "Edit Item" %></h2>
<%= render 'form' %>

app/views/items/index.html.erb
<div class="header">
	<h2><%= page_title "Your Items" %></h2>
	<%#= button_link_to "New Item", new_item_path, :class => 'minimal' %>
</div>	

<ul class="items">
	<%= render @items %>
</ul>

app/views/items/new.html.erb
<h2 class="title"><%=title "Add New Item" %></h2>
<%= render 'form' %>

app/views/items/show.html.erb
<div class="item clearfix">
	<%= image_tag(@item.image, :class => 'thumb') %>
	<div class="content">

		<div class="status">
			<% if current_user.has_this?(@item) %>
				<%= button_to "Remove This Item", user_item_path(@item), :method => :delete %>
			<% else %>
				<%= button_to "Add This Item", user_items_path(:item_id => @item.id) %>
			<% end %>
		</div>

		<h2><%= @item.title %></h2>
		<%= link_to @item.url, @item.url %>
		<p>
			<%= @item.description %>
		</p>	
	</div>	
</div>

<h3>Entries about This Item</h3>

<ul class="entries">
	<%= render @item.entries %>
</ul>	

<hr />
<%= button_link_to "Add Entry about This", new_item_entry_path(@item), :class => 'minimal' %>

<div class="votes">
	<h5>Vote</h5>
	<% if current_user && current_user.voted?(@item) %>
		당신은 이 항목을 <%= current_user.up_voted?(@item) ? '좋아' : '싫어' %> 합니다. 
		<%= link_to "취소", item_vote_path(@item, 1), :method => 'delete' %>
	<% else %>
		<%= link_to "좋아요", item_votes_path(@item, :flag => 'up'), :method => 'post' %>: <%#= @item.up_votes %> |
		<%= link_to "싫어요", item_votes_path(@item, :flag => 'down'), :method => 'post' %>: <%#= @item.down_votes %>
	<% end %>	
</div>	


<h3>People who add this item</h3>
<ul>
	<% @users.each do |user| %>
	<li><%= user %></li>
	<% end %>
</ul>		